/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NivelMedio;

import javax.swing.JToggleButton;

/**
 *
 * @author aldav
 */
public class Introducion1 extends javax.swing.JFrame {

    /**
     * Creates new form Introducion1
     */
    public Introducion1() {
        this.setSize(748, 519);// Tamaño de la dimensicion.
        this.setLocationRelativeTo(null);// Se utiliza para centrar la ventana de Jframe.
        this.setTitle("Juego Escapando de SAW");
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1Texto1 = new javax.swing.JLabel();
        jLabel2Texto2 = new javax.swing.JLabel();
        jLabel3Texto3 = new javax.swing.JLabel();
        jLabel4Texto4 = new javax.swing.JLabel();
        jButton1Jugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1Cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1Texto1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1Texto1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1Texto1.setText(" Para pasar al siguiente nivel , tienes que resolver este acertijo.");
        jPanel1.add(jLabel1Texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 740, 70));

        jLabel2Texto2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2Texto2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2Texto2.setText("Tienes que formar  dos cuadros .");
        jPanel1.add(jLabel2Texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 370, 50));

        jLabel3Texto3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3Texto3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3Texto3.setText("Reglas del juego :");
        jPanel1.add(jLabel3Texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 70));

        jLabel4Texto4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4Texto4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4Texto4.setText("  Solo puede quitar dos bloques y no te pueden sobrar bloques.");
        jPanel1.add(jLabel4Texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 700, 60));

        jButton1Jugar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1Jugar.setForeground(new java.awt.Color(255, 0, 0));
        jButton1Jugar.setText("Jugar");
        jButton1Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1JugarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 110, -1));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Solo tienes  una opcion, Si pierdes se devolver al inicio del nivel");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 700, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images5.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 190, 150));

        jButton1Cerrar.setBackground(new java.awt.Color(255, 0, 0));
        jButton1Cerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1Cerrar.setText("X");
        jButton1Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1JugarActionPerformed
         /// Con este Objeto me puedo pasar de pantallas con el boton indicado.
         dispose();
        Juego1 juego1 = new Juego1();
         juego1.setVisible(true);
         
    }//GEN-LAST:event_jButton1JugarActionPerformed

    private void jButton1CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CerrarActionPerformed
         
        /// Con este Objeto me puedo pasar de de inicio con el boton indicado.
        Nivel_Intermedio juego1 = new Nivel_Intermedio();
         juego1.setVisible(true);
    }//GEN-LAST:event_jButton1CerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Introducion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Introducion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Introducion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Introducion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Introducion1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Cerrar;
    private javax.swing.JButton jButton1Jugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Texto1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2Texto2;
    private javax.swing.JLabel jLabel3Texto3;
    private javax.swing.JLabel jLabel4Texto4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
