package NivelMedio;


import java.awt.Image;
import static javax.swing.Action.DEFAULT;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author aldav
 */
public class Juego1 extends javax.swing.JFrame {

    private Nivel1 controlador;

    private ImageIcon imagen;
    private Icon icono;

    public Juego1() {

        // this.add(mcolor);/// se agrego degradado
        this.setSize(748, 519);
        this.setLocationRelativeTo(this);// Se utiliza para centrar la ventana de Jframe.
        this.setTitle("Juego Escapando de SAW");
        //this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);///se agrego degradado
        initComponents();

        // Para insertar imagenes
        ImageIcon imagen3 = new ImageIcon(getClass().getResource("/Imagenes/1111images.jpg"));
        Icon fondo2 = new ImageIcon(imagen3.getImage().getScaledInstance(Ilimagen10.getWidth(), Ilimagen10.getHeight(), Image.SCALE_DEFAULT));
        Ilimagen10.setIcon(fondo2);
        this.repaint();

        controlador = new Nivel1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        Iblimagen1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        Iblimagen2 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton13Cierre = new javax.swing.JButton();
        Ilimagen10 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descargaSAW3.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setBackground(new java.awt.Color(255, 0, 0));
        jButton14.setText("jButton4");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 20, 140));

        jButton15.setBackground(new java.awt.Color(255, 0, 51));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 240, 20));

        jButton16.setBackground(new java.awt.Color(255, 0, 0));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 240, 20));

        jButton17.setBackground(new java.awt.Color(255, 0, 0));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 230, 20));

        jButton18.setBackground(new java.awt.Color(255, 0, 0));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 20, 190));

        jButton19.setBackground(new java.awt.Color(255, 0, 0));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 20, 170));

        Iblimagen1.setBackground(new java.awt.Color(255, 0, 0));
        Iblimagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iblimagen1ActionPerformed(evt);
            }
        });
        jPanel1.add(Iblimagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 230, 20));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 20, 160));

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 240, 20));

        jButton21.setBackground(new java.awt.Color(255, 0, 0));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 230, 20));

        Iblimagen2.setBackground(new java.awt.Color(255, 0, 0));
        Iblimagen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iblimagen2ActionPerformed(evt);
            }
        });
        jPanel1.add(Iblimagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 20, 190));

        jButton23.setBackground(new java.awt.Color(255, 0, 0));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 20, 170));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Comprobar Juego");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 120, 30));

        jButton13Cierre.setBackground(new java.awt.Color(255, 0, 0));
        jButton13Cierre.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jButton13Cierre.setText("X");
        jButton13Cierre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13CierreActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13Cierre, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 40, -1));

        Ilimagen10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sawpequeña.jpg"))); // NOI18N
        Ilimagen10.setText("jLabel2");
        jPanel1.add(Ilimagen10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 90, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        manejarClick(jButton5, 5);


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        manejarClick(jButton15, 15);

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:

        manejarClick(jButton16, 16);


    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        manejarClick(jButton17, 17);

    }//GEN-LAST:event_jButton17ActionPerformed

    private void Iblimagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iblimagen1ActionPerformed
        // TODO add your handling code here:
        manejarClick(Iblimagen1, 1);


    }//GEN-LAST:event_Iblimagen1ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        manejarClick(jButton21, 21);


    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        manejarClick(jButton23, 23);


    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!controlador.puedeSeleccionar()) {
            if (controlador.esGanador()) {
                JOptionPane.showMessageDialog(null, "",
                        "Ganaste",JOptionPane.WARNING_MESSAGE,new ImageIcon("src/Imagenes/ganaste1.png"));
                dispose();
                Introducion2 introduccion2 = new Introducion2();
                introduccion2.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "",
                        "Perdiste",JOptionPane.WARNING_MESSAGE, new ImageIcon("src/Imagenes/Perdiste.png"));
                dispose();
                Introducion1 introduccion2 = new Introducion1();
                introduccion2.setVisible(true);
            }
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Iblimagen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iblimagen2ActionPerformed
        // TODO add your handling code here:
        manejarClick(Iblimagen2, 2);

        ImageIcon imagen2 = new ImageIcon(getClass().getResource("/Imagenes/1.jpg"));
        Icon fondo1 = new ImageIcon(imagen2.getImage().getScaledInstance(Iblimagen2.getWidth(), Iblimagen2.getHeight(), Image.SCALE_DEFAULT));
        Iblimagen2.setIcon(fondo1);
        this.repaint();


    }//GEN-LAST:event_Iblimagen2ActionPerformed

    private void jButton13CierreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13CierreActionPerformed
        /// Con este Objeto me puedo pasar de de inicio con el boton indicado.
        Nivel_Intermedio juego1 = new Nivel_Intermedio();
        juego1.setVisible(true);
    }//GEN-LAST:event_jButton13CierreActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        manejarClick(jButton18, 18);

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:

        manejarClick(jButton19, 19);

    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        manejarClick(jButton4, 4);

    }//GEN-LAST:event_jButton4ActionPerformed
    private void manejarClick(JButton boton, Integer numeroBoton) {
        if (controlador.puedeSeleccionar()) {
            boton.setVisible(false);
            controlador.aumentarContador(numeroBoton);

        }

    }

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:

        manejarClick(jButton14, 14);


    }//GEN-LAST:event_jButton14ActionPerformed
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego1().setVisible(true);
            }
        });
    }

    private void pintarImagen(JLabel jLabel1, String ruta) {

        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        jLabel1.getWidth(),
                        jLabel1.getHeight(),
                        Image.SCALE_DEFAULT
                )
        );
        jLabel1.setIcon(this.icono);
        this.repaint();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Iblimagen1;
    private javax.swing.JButton Iblimagen2;
    private javax.swing.JLabel Ilimagen10;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13Cierre;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
