
package NivelMedio;

import java.awt.Color;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author aldav
 */
public class Nivel_Intermedio extends javax.swing.JFrame {
    
   // FondoPanel fondo1 = new FondoPanel();
    
     public JPanel panel;
      
    /**
     * Creates new form Nivel_Intermedio
     */
     
     
    public  Nivel_Intermedio() {
        this.setSize(748, 519);// Tamaño de la dimensicion.
        
        this.setLocationRelativeTo(null);// Se utiliza para centrar la ventana de Jframe.
        this.setTitle("Juego Escapando de SAW");// Nombre de la venta del Jframe.
      //  this.setContentPane(fondo1);
        initComponents();
     
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Imagen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1TextoInicio = new javax.swing.JLabel();
        jButton1Siguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1Cerre = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Imagen.setForeground(new java.awt.Color(255, 255, 255));
        Imagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\aldav\\OneDrive - Universidad Fidélitas\\Escritorio\\Juego-Escapando-de-SAW-master\\src\\Imagenes\\descarga.png")); // NOI18N
        jPanel1.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 300, 160));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1TextoInicio.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jLabel1TextoInicio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1TextoInicio.setText(" Listo para jugar o morir !!!!!");
        jPanel2.add(jLabel1TextoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 640, 130));
        jLabel1TextoInicio.getAccessibleContext().setAccessibleName("Bienvenidos al Juego de SAW!!!!!!                                                                         Listo para jugar o morir !!!!!");

        jButton1Siguiente.setBackground(new java.awt.Color(255, 0, 51));
        jButton1Siguiente.setFont(new java.awt.Font("Viner Hand ITC", 1, 14)); // NOI18N
        jButton1Siguiente.setForeground(new java.awt.Color(255, 255, 255));
        jButton1Siguiente.setText("Siguiente");
        jButton1Siguiente.setFocusTraversalPolicyProvider(true);
        jButton1Siguiente.setSelected(true);
        jButton1Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SiguienteActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 110, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 820, 220));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nivel  facil");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 370, 50));

        jButton1Cerre.setBackground(new java.awt.Color(204, 0, 0));
        jButton1Cerre.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1Cerre.setText("X");
        jButton1Cerre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1CerreActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1Cerre, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SiguienteActionPerformed
        dispose();
        /// Con este Objeto me puedo pasar de pantallas con el boton indicado.
        Introducion1 juego = new Introducion1();
         juego.setVisible(true);
    }//GEN-LAST:event_jButton1SiguienteActionPerformed

    private void jButton1CerreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1CerreActionPerformed
        JButton boton3 = new JButton();

        boton3.setEnabled(false); // Establecemos el encendido del boton.
        boton3.setBorder(BorderFactory.createLineBorder(Color.yellow, 3));/// se utiliza para darle color a borde del boton

    }//GEN-LAST:event_jButton1CerreActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nivel_Intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nivel_Intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nivel_Intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nivel_Intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nivel_Intermedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton jButton1Cerre;
    private javax.swing.JButton jButton1Siguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1TextoInicio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

 /* class FondoPanel extends JPanel{
  
   private Image imagen;
   
   @Override
   public void paint (Graphics g){
   
       imagen = new ImageIcon(getClass().getResource("/Imagenes/imagen.SAW5jpg.jpg")).getImage();
       g.drawImage(imagen, 0, 0, getWidth(), getHeight(),this);
       
       setOpaque(false);
       
       super.paint(g);
   
   }
  }*/
}
