/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MenuInicio;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import NivelFacil.*;

/**
 *
 * @author zujeily
 */
public class BienvenidoUsuarioNuevoOViejo extends javax.swing.JFrame {
Fondo fondoSaw=new Fondo();
    /**
     * Creates new form BienvenidoUsuarioNuevoOViejo
     */
    public BienvenidoUsuarioNuevoOViejo() {
        this.setContentPane(fondoSaw);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Juego Escapando de SAW");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BienvenidoMen = new javax.swing.JLabel();
        BienvenidoNomUs = new javax.swing.JLabel();
        JuegoNuevo = new javax.swing.JButton();
        RegresarVentanaInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BienvenidoMen.setForeground(new java.awt.Color(255, 255, 255));
        BienvenidoMen.setText("Bienvenido");

        BienvenidoNomUs.setText("jLabel1");

        JuegoNuevo.setBackground(new java.awt.Color(0, 0, 0));
        JuegoNuevo.setForeground(new java.awt.Color(255, 0, 0));
        JuegoNuevo.setText("Iniciar Partida Nueva");
        JuegoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuegoNuevoActionPerformed(evt);
            }
        });

        RegresarVentanaInicio.setForeground(new java.awt.Color(255, 255, 255));
        RegresarVentanaInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prev_previous_icon.png"))); // NOI18N
        RegresarVentanaInicio.setText("Regresar");
        RegresarVentanaInicio.setContentAreaFilled(false);
        RegresarVentanaInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegresarVentanaInicio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RegresarVentanaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarVentanaInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(BienvenidoMen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BienvenidoNomUs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 534, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JuegoNuevo)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RegresarVentanaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BienvenidoMen)
                    .addComponent(BienvenidoNomUs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 374, Short.MAX_VALUE)
                .addComponent(JuegoNuevo)
                .addGap(18, 18, 18)
                .addComponent(RegresarVentanaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarVentanaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarVentanaInicioActionPerformed
        // Tregresar al inicio
        LoginDeUsuarioInicio LUI = new LoginDeUsuarioInicio();
        LUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarVentanaInicioActionPerformed

    private void JuegoNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuegoNuevoActionPerformed
        // Ingresa a el primer nivel 
        Parte1 N1 = new Parte1(); 
        N1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_JuegoNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BienvenidoUsuarioNuevoOViejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BienvenidoUsuarioNuevoOViejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BienvenidoUsuarioNuevoOViejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BienvenidoUsuarioNuevoOViejo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BienvenidoUsuarioNuevoOViejo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BienvenidoMen;
    private javax.swing.JLabel BienvenidoNomUs;
    private javax.swing.JButton JuegoNuevo;
    private javax.swing.JButton RegresarVentanaInicio;
    // End of variables declaration//GEN-END:variables

class Fondo extends JPanel{
     private Image EscapandosawImage;         

     @Override
     public void paint (Graphics imagen){
         
     EscapandosawImage =new ImageIcon(getClass().getResource("/imagenes/sawRegistroUsuario.jpg")).getImage();
     imagen.drawImage(EscapandosawImage, 0, 0, getWidth(), getHeight(), this);
     setOpaque(false);
     super.paint(imagen);


     }}

}
