/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MenuInicio;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import conexionMYSQL.*;

/**
 *
 * @author zujeily
 */
public class LoginDeUsuarioInicio extends javax.swing.JFrame {
FondoLI LI= new FondoLI();
MYSQLconexion conn=new MYSQLconexion();


    /**
     * Creates new form LoginDeUsuarioInicio
     */
    public LoginDeUsuarioInicio() {
        this.setContentPane(LI); 
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Juego Escapando de SAW");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoGJS = new javax.swing.JLabel();
        JSSmallLU = new javax.swing.JLabel();
        PassLU = new javax.swing.JLabel();
        IniSesLU = new javax.swing.JLabel();
        UsuaLU = new javax.swing.JLabel();
        IngreUFieldLU = new javax.swing.JTextField();
        PasswordFieldLU = new javax.swing.JPasswordField();
        EnterLU = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        UsuarioNuevoLU = new javax.swing.JButton();
        RegresarLDUI = new javax.swing.JButton();
        MensajePositivo = new javax.swing.JLabel();
        MensajeNegativo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(717, 540));

        LogoGJS.setIcon(new javax.swing.ImageIcon("/home/zujeily/Downloads/Cliente Servidor/personajes historia y proyecto Escape Saw info /JS.png")); // NOI18N

        JSSmallLU.setIcon(new javax.swing.ImageIcon("/home/zujeily/Downloads/Cliente Servidor/personajes historia y proyecto Escape Saw info /sawlogosmallLU.png")); // NOI18N

        PassLU.setFont(new java.awt.Font("Gayathri Thin", 1, 18)); // NOI18N
        PassLU.setForeground(new java.awt.Color(255, 0, 0));
        PassLU.setText("Contraseña");

        IniSesLU.setFont(new java.awt.Font("Gayathri Thin", 1, 24)); // NOI18N
        IniSesLU.setForeground(new java.awt.Color(255, 0, 0));
        IniSesLU.setText("INICIAR SESIÓN");

        UsuaLU.setFont(new java.awt.Font("Gayathri Thin", 1, 18)); // NOI18N
        UsuaLU.setForeground(new java.awt.Color(255, 0, 0));
        UsuaLU.setText("Usuario");

        IngreUFieldLU.setBackground(new java.awt.Color(0, 0, 0));
        IngreUFieldLU.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        IngreUFieldLU.setForeground(new java.awt.Color(255, 0, 0));
        IngreUFieldLU.setText(" Ingrese su nombre");
        IngreUFieldLU.setBorder(null);
        IngreUFieldLU.setCaretColor(new java.awt.Color(255, 0, 0));
        IngreUFieldLU.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        IngreUFieldLU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngreUFieldLUActionPerformed(evt);
            }
        });

        PasswordFieldLU.setBackground(new java.awt.Color(0, 0, 0));
        PasswordFieldLU.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        PasswordFieldLU.setForeground(new java.awt.Color(255, 0, 0));
        PasswordFieldLU.setText("jPasswordField1");
        PasswordFieldLU.setBorder(null);
        PasswordFieldLU.setCaretColor(new java.awt.Color(255, 0, 0));

        EnterLU.setBackground(new java.awt.Color(0, 0, 0));
        EnterLU.setFont(new java.awt.Font("Gayathri Thin", 1, 18)); // NOI18N
        EnterLU.setForeground(new java.awt.Color(255, 0, 0));
        EnterLU.setText("Entrar");
        EnterLU.setOpaque(false);
        EnterLU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterLUActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        UsuarioNuevoLU.setBackground(new java.awt.Color(0, 0, 0));
        UsuarioNuevoLU.setFont(new java.awt.Font("Gayathri Thin", 1, 18)); // NOI18N
        UsuarioNuevoLU.setForeground(new java.awt.Color(255, 0, 0));
        UsuarioNuevoLU.setText("Usuario Nuevo");
        UsuarioNuevoLU.setBorderPainted(false);
        UsuarioNuevoLU.setOpaque(false);
        UsuarioNuevoLU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioNuevoLUActionPerformed(evt);
            }
        });

        RegresarLDUI.setFont(new java.awt.Font("Gayathri Thin", 1, 18)); // NOI18N
        RegresarLDUI.setForeground(new java.awt.Color(255, 0, 0));
        RegresarLDUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prev_previous_icon.png"))); // NOI18N
        RegresarLDUI.setText("Regresar");
        RegresarLDUI.setContentAreaFilled(false);
        RegresarLDUI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegresarLDUI.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RegresarLDUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarLDUIActionPerformed(evt);
            }
        });

        MensajePositivo.setVisible(false);
        MensajePositivo.setFont(new java.awt.Font("Gayathri Thin", 1, 24)); // NOI18N
        MensajePositivo.setForeground(new java.awt.Color(255, 0, 0));
        MensajePositivo.setText("Welcome back whuajajajajaj!");

        MensajeNegativo.setVisible(false);
        MensajeNegativo.setFont(new java.awt.Font("Gayathri Thin", 1, 14)); // NOI18N
        MensajeNegativo.setForeground(new java.awt.Color(255, 0, 0));
        MensajeNegativo.setText("Parece que no existe el usuario, considera crear un usuario nuevo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(JSSmallLU)
                        .addGap(18, 18, 18)
                        .addComponent(IniSesLU, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PassLU, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordFieldLU, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsuaLU, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(IngreUFieldLU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(EnterLU, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(UsuarioNuevoLU, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(RegresarLDUI, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoGJS, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MensajePositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MensajeNegativo, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JSSmallLU, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IniSesLU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(UsuaLU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IngreUFieldLU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(PassLU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PasswordFieldLU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(EnterLU, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UsuarioNuevoLU)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RegresarLDUI, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(MensajePositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MensajeNegativo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogoGJS, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngreUFieldLUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngreUFieldLUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngreUFieldLUActionPerformed

    private void UsuarioNuevoLUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioNuevoLUActionPerformed
        // Telleva a clase Crear Usuario Nuevo
        CrearUsuarioNuevo CUN =new CrearUsuarioNuevo();
        CUN.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_UsuarioNuevoLUActionPerformed

    private void RegresarLDUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarLDUIActionPerformed
        // Este boton regresa a la Ventana de InicioFrame
        VentanaDeInicio VDI =new VentanaDeInicio();
        VDI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RegresarLDUIActionPerformed

    private void EnterLUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterLUActionPerformed
        //verificar usuario y ingresar si true 
         BienvenidoUsuarioNuevoOViejo BU = new BienvenidoUsuarioNuevoOViejo();
        conn.createConnetion();
        if (conn.VerificarUser(IngreUFieldLU.getText())){
            MensajePositivo.setVisible(true);
            MensajeNegativo.setVisible(false);
            BU.setVisible(true);
            this.setVisible(false);
            
        }else{
           MensajeNegativo.setVisible(true); 
           MensajePositivo.setVisible(false);
        }
    }//GEN-LAST:event_EnterLUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDeUsuarioInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDeUsuarioInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDeUsuarioInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDeUsuarioInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDeUsuarioInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnterLU;
    private javax.swing.JTextField IngreUFieldLU;
    private javax.swing.JLabel IniSesLU;
    private javax.swing.JLabel JSSmallLU;
    private javax.swing.JLabel LogoGJS;
    private javax.swing.JLabel MensajeNegativo;
    private javax.swing.JLabel MensajePositivo;
    private javax.swing.JLabel PassLU;
    private javax.swing.JPasswordField PasswordFieldLU;
    private javax.swing.JButton RegresarLDUI;
    private javax.swing.JLabel UsuaLU;
    private javax.swing.JButton UsuarioNuevoLU;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

     class FondoLI extends JPanel{
     private Image Logo;         

     @Override
     public void paint (Graphics imagen){
         
     Logo =new ImageIcon(getClass().getResource("/imagenes/ES.png")).getImage();
     imagen.drawImage(Logo, 0, 0, getWidth(), getHeight(), this);
     setOpaque(false);
     super.paint(imagen);
     }}

}
